
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Wordpress-K8s-HLM
  description: Cloudify helm-wordpress blueprint. Installs Wordpress Helm chart on top of Kubernetes cluster.
  tags:
    - tosca
    - cloudify
  links:
    - url: http://3.96.109.197/console/page/blueprints_blueprint/Wordpress-K8s-HLM?c=%5B%7B%22context%22%3A%7B%7D%7D%2C%7B%22context%22%3A%7B%22blueprintId%22%3A%22Wordpress-K8s-HLM%22%7D%2C%22pageName%22%3A%22Wordpress-K8s-HLM%22%7D%5D#!
      title: Deploy component
      icon: user
spec:
  type: service
  lifecycle: production
  owner: team-a
